const mongoose=require('mongoose')

const formModel=new mongoose.Schema({
    
    nombre_formulario:{
        type:String
    },
    numero_operacion:{
        type:String
    },
    numero_producto:{
        type:String
    },
    materia_prima0:{
        type:String
    },
    materia_prima1:{
        type:String
    },
    materia_prima2:{
        type:String
    },
    materia_prima3:{
        type:String
    },
    materia_prima4:{
        type:String
    },
    materia_prima5:{
        type:String
    },
    numero_inyectora:{
        type:String
    },
    numero_molde:{
        type:String
    },
    tiempo_ciclo:{
        type:String
    },
    aditivo:{
        type:String
    },
    registrado_por:{
        type:String
    },
 //Dispositivos utilizados
     pico_de_inytectora:{
        type:String
    },
     microgel_0:{
        type:String
    },
     microgel_1:{
        type:String
    },
     regoplas:{
        type:String
    },
     robot:{
        type:String
    },
     otro:{
        type:String
    },
 //Temperaturas del proceso
     temp_plato_fijo:{
        type:String
    },
     temp_plato_movil:{
        type:String
    },
     temp_masa_fundida:{
        type:String
    },
     tablero_colada_caliente:{
        type:String
    },
     temp_horno:{
        type:String
    },
 //Parametros del proceso
     tpo_ciclo_optimo:{
        type:String
    },
     tpo_ciclo_actual:{
        type:String
    },
     tpo_inyeccion:{
        type:String
    },
     tpo_extrusor:{
        type:String
    },
     tpo_enfriamiento:{
        type:String
    },
     cojin:{
        type:String
    },
     pico_presion:{
        type:String
    },
     punto_transferencia:{
        type:String
    },
     fuerza_cierre:{
        type:String
    },
     tamano_dosific:{
        type:String
    },
     contrapresion:{
        type:String
    },
     presion_empaque:{
        type:String
    },
     tpo_retencion:{
        type:String
    },
     tipo_expulsion:{
        type:String
    },
 //Cavidades habilitadas en produccion
     cavidades:{
        type:String
    },
     observaciones:{
        type:String
    }
})
module.exports=mongoose.model('form',formModel)